### ISSUE TITLE
Te hoog energieverbruik bij beschikbaar komen oliepomp V2

### ISSUE THREAD

**Issue by TommyboyNL** [HermanRonk/Clickfarm#11]
Bron: https://gathering.tweakers.net/forum/list_message/55307227#55307227
"Sinds ik oliepomp v2 kan kopen maar nog niet heb gedaan is mijn olieverbruik van 161 naar 1630 gegaan, net zo hoog als mijn energie. Hoe komt dat?"

Zelf zie ik dat ook. 250 standaard energiecentrales brengen mijn olieverbruik naar 2500 in plaats van 250.

**Comment by HermanRonk** [comment]
Ik kan niet vinden waar dit door komt.

Waar zie je het hoge olieverbruik staan? Is dat helemaal bovenin:
![image](https://user-images.githubusercontent.com/2781343/42721209-c1a3b2ea-8736-11e8-9f31-b980d3c5ec05.png)

**Comment by HermanRonk** [comment]
Dit zou nu opgelost moeten zijn: https://github.com/HermanRonk/Clickfarm/commit/8f7362ac9506d46e22707054a84922fc0f71e5e7
