### ISSUE TITLE
Browser niet compatible (sliders)

### ISSUE THREAD

**Issue by HermanRonk** [HermanRonk/Clickfarm#13]
Niet in alle browsers werken de huidige sliders voor de automatische verkoop van resources goed. Ik heb hier zelf wat in elkaar geprutst, maar als iemand een betere implementatie heeft kan dit nog wel wat verbetering gebruiken.

![image](https://user-images.githubusercontent.com/2781343/42693237-c4c56384-86ae-11e8-9644-69eb7c2e0ed1.png)

**Comment by Marcade80** [comment]
Sliders werkte voor mij in Edge/FF/Chrome maar niet in IE11 en de sliders zag er verschillend uit. Veranderd naar Bootstrap-slider die er in alle browsers voor mij hetzelfde uitziet & werkt. Hopelijk werkt die nu ook in de browser(s) waar jij zag dat ie. kaput was.
