### ISSUE TITLE
Suggestie: Cache probleem bij updates van websites

### ISSUE THREAD

**Issue by Marcade80** [HermanRonk/Clickfarm#14]
Browsers houden ervan om web bestanden lokaal op te slaan en alleen te verversen als ze nieuw zijn. Specifiek de CSS/JavaScript files. Dat kan nog wel is vreemd gedrag opleveren bij mensen.

Een mogelijke oplossing is om de index.html -> index.php te veranderen, zodat we PHP kunnen gebruiken en een 'modified' timestamp achter elke CSS/Javascript kunnen plaatsen. Doordat er een timestamp toegevoegd word; word het bestand lokaal ververst door web browsers als de timestamp niet matched met het lokaal opgeslagen bestand. Klinkt ingewikkelder dan het eigenlijk is.

Voorbeeld in index.html (wat PHP word):
`<link rel="stylesheet" href="./css/style.css">`
naar
`<link rel="stylesheet" href="./css/style.css?<?php echo filemtime('./css/style.css')?>">`

Wat door PHP vertaald word naar:
`<link rel="stylesheet" href="./css/style.css?1531493874">`

PHP functie filemtime() geeft de 'last modified' tijd/datum van het bestand terug in epoch seconden. Dus zodra iemand het bestand update; verandert het nummer automatisch en weet je zeker dat pagina bezoekers het laatste bestand zullen downloaden.

**Comment by HermanRonk** [comment]
Ik ben op zich niet tegen, de webserver draait ook PHP (voor de backend onder andere). Het is alleen wel even wat werk om dit te realiseren denk ik..
