### ISSUE TITLE
Automatische verkoopprijs kunststof wordt vergeten bij reload

### ISSUE THREAD

**Issue by TommyboyNL** [HermanRonk/Clickfarm#15]
Voor olie, bloem, en pasta wordt de prijs waarbij automatisch verkocht word wel onthouden tijdens een reload, voor kunststof niet.

**Comment by Marcade80** [comment]
Net al gefixed in de commit.

**Comment by HermanRonk** [comment]
De bedragen worden goed onthouden, maar de slider staat wel verkeerd:

![image](https://user-images.githubusercontent.com/2781343/42703855-11af9d3a-86ce-11e8-9784-a324de6bd90b.png)

@Marcade80 wil je daar even een blik op werpen?

**Comment by Marcade80** [comment]
Hmm dat werkt wel goed in IE/FF/Chrome/Edge; mss. refreshen met SHIFT-F5 ?

de sliders behoren ook groter te zijn dan dat.

**Comment by Marcade80** [comment]
Is dit nog steeds een probleem?

**Comment by HermanRonk** [comment]
Yep, ik blijf dit hebben in zowel Chrome als Firefox. Of in ieder geval deels, de balken hebben nu wel de goede lengte.  Het vreemde is dat wanneer in in Firefox een savegame importeer de sliders eerst goed staan, en vervolgens wanneer ik de pagina reload de sliders allemaal aan het einde staan. In Chrome staan ze meteen na de import al helemaal achteraan.

**Comment by Marcade80** [comment]
Vreemd. Ik test in de laatste versies van Chrome & FF; for IE test ik in Edge & IE11; allevier inderdaad ook herladen ed. en geen vreemd gedrag.

Desalnietemin toch aangepast; zag dat bootstrap 4.1 zelf ook sliders heeft dus laten we dat is proberen. (btw. ook funny gedrag omtrend onchange() en oninput() dus beide toegevoegd in input element)

**Comment by HermanRonk** [comment]
Dit heeft inderdaad het gewenste effect. Volgens mij werkt het nu naar behoren:
![image](https://user-images.githubusercontent.com/2781343/42860418-b4929404-8a56-11e8-94b5-d5822d73909f.png)
