### ISSUE TITLE
Meldingen geen voorraad blijft staan.

### ISSUE THREAD

**Issue by Hengbers** [HermanRonk/Clickfarm#17]
Op het moment er een pop up melding is blijft deze staan. Mogelijk om dit max 5 seconde te laten staan en dan te verdwijnen.

**Comment by HermanRonk** [comment]
Dit is een bewuste keuze, wanneer je het spel laat lopen zonder dat je er bij bent wil je kunnen zien wat de laatste meldingen waren.

Als iemand dit wil implementeren dan zou het een optie worden in het game menu wat mij betreft.

**Comment by Marcade80** [comment]
laatste pull() request laat berichten na 10 seconden verdwijnen, mits het in het menu is aangezet.
