### ISSUE TITLE
Farmrobots en farms gebruiken nog eigen timers

### ISSUE THREAD

**Issue by HermanRonk** [HermanRonk/Clickfarm#2]
Zowel de farms als de farmrobot gebruiken nu nog eigen timers, 

Het zou netter zijn om dit onder te brengen in de centrale timer. Dit voorkomt timing issue's

Het betreft onder andere deze code:
```

    work: function () {
        if (objFarmRobot.amount == 0) {
            return 0;
        };
        var tempEnergy = +objEnergy.available;
        objFarmRobot.activeRobots = Math.floor(+tempEnergy / +objFarmRobot.robotEnergy);
        if (+objFarmRobot.activeRobots > +objFarmRobot.robots) {
            objFarmRobot.activeRobots = +objFarmRobot.robots;
        };
        var robotEnergyUsage = +objFarmRobot.activeRobots * +objFarmRobot.robotEnergy;
        objEnergy.use(+robotEnergyUsage, "Farmrobot");
        if ((+objFarmRobot.activeRobots * +objFarmRobot.robotCap) > +objFarmland.amount) {
            var activeFields = +objFarmland.amount;
        } else {
            var activeFields = +objFarmRobot.activeRobots * +objFarmRobot.robotCap;
        }
        var robotLoop = setInterval(
            function () {
                objFarmRobot.robotTimer--;
                objFarmRobot.timerCountdown();
                if (objFarmRobot.robotTimer < 1) {
                    clearInterval(robotLoop);
                    //nog rekening houden met max aan de hand van aanwezige velden.
                    var production = (+activeFields * +objFarmland.harvest);
                    objGrainSilo.fill(production);
                    objGrainSilo.show();
                    objFarmRobot.robotTimer = 10;
                    objFarmRobot.work();
                }
            }, 1000)
},
```

**Comment by Marcade80** [comment]
Er zitten meerdere setIntervals in de code; niet alleen voor de farms:
- robotLoop (regel 405)
- farmLoop (regel 774)
- grindLoop (regel 870)
- nog een grindLoop (??) (regel 935)
- researchLoop (regel 1701)
- nog een researchLoop (regel 2105)
- prospectLoop (regel 2225)

behoren die *allemaal* onder de centrale timer? Ga er vanuit dat LoopsProduction (regel 3895) de centrale timer is ..

**Comment by HermanRonk** [comment]
Klopt, en het lijkt me netter om dat allemaal centraal te doen zodat je geen afwijkingen hebt in timings

**Comment by Marcade80** [comment]
de automatische graanvermaling volgt hetzelfde principe as de manuele. Elke 10 seconden kan er 1000kg graan vermalen worden. Manueel hoort iemand elke 10 seconden op de knop te drukken.

Als ik 1000kg graan heb; vermaalt de molen 100kg graan per 1 seconden, voor 10 seconden lang.
Als ik maar 100kg graan heb, vermaalt de molen maar 10kg graan per 1 seconden, voor 10 seconden lang; dit terwijl we practisch gezien weten dat de molen 100kg graan per seconden aankan.. Het voelt een beetje raar dat een molen 10 seconden nodig heeft, zelfs voor een handjevol graan.

Klopt dit?

Voor de automatische graanvermaling zie ik het nut er niet van in om de 10 seconden logika aan te houden; sinds het gewoon een continue process is. Alleen volgt het het bovenstaande principe ook; als er nog maar een handjevol graan is, wil die er ook nog 10 seconden over doen.

Voor automatisch graanvermaling lijkt me logischer om gewoon 1 seconden -> 100kg graanvermaling te doen; sinds de logika elke seconden checkt of er graan & energie is? Of wil je perse de 10 seconden logika handhaven?

**Comment by Marcade80** [comment]
laatste pull request brengt alles onder een loop(); de grind logica is vooralsnog gehandhaafd

**Comment by HermanRonk** [comment]
> Voor automatisch graanvermaling lijkt me logischer om gewoon 1 seconden -> 100kg graanvermaling te doen; sinds de logika elke seconden checkt of er graan & energie is? Of wil je perse de 10 seconden logika handhaven?

Het is mij om het even eigenlijk, ik heb er geen probleem mee als de logica aangepast wordt naar 100kg per seconde om te zetten.
