### ISSUE TITLE
Automatische verkoop Pasta/kunststof wordt weergegeven als handmatig

### ISSUE THREAD

**Issue by TommyboyNL** [HermanRonk/Clickfarm#20]
Aangezien de code voor kunststof gekopieerd is van pasta, is dit dezelfde bug. Dit heeft te maken met de verkooproutine die alleen opties kent voor handmatige verkoop, en overschot verkoop. De code voor handmatige verkoop wordt aangeroepen bij een automatische verkoop.

**Comment by HermanRonk** [comment]
Ik zal dit vandaag even oppakken
