### ISSUE TITLE
Weergaveprobleem (blokken missen)

### ISSUE THREAD

**Issue by HermanRonk** [HermanRonk/Clickfarm#23]
https://gathering.tweakers.net/forum/list_message/55867017#55867017

Er lijkt sinds de nieuwe level verwerking wat verkeerd te gaan. Bijvoorbeeld steenkool en de opmaak van het kernenergie blok werken niet meer naar behoren. @Marcade80 zie je kans om hier even naar te kijken? Dit heeft dus vermoedelijk te maken met #1

**Comment by Marcade80** [comment]
Is het nog steeds een probleem na de laatste pull? Als het goed is is de layout weer als vanouds.

**Comment by HermanRonk** [comment]
Het is inderdaad opgelost
