### ISSUE TITLE
Waste pellets teller breekt bij 1000+ kernreactoren

### ISSUE THREAD

**Issue by TommyboyNL** [HermanRonk/Clickfarm#3]
Situatie: 1100 kernreactoren. Elke seconde wordt er 100 bij mijn waste pellets opgeteld, en 1 bij mijn waste staven. Het lijkt er op dat er per tick maar 1 staaf van de waste pallets naar de afvalopslag verplaatst kan worden.

**Comment by HermanRonk** [comment]
Op https://game-dev.hotellan.nl draait nu de versie met deze fix
