### ISSUE TITLE
Excessieve onnodige AJAX calls

### ISSUE THREAD

**Issue by Marcade80** [HermanRonk/Clickfarm#32]
https://github.com/HermanRonk/Clickfarm/blob/bee1d7e91b1530158bf57761e00d5332aac4e8f8/inc/base.js#L4018

Volgens mij zorgt die lijn ervoor dat je *elke seconden* een request maakt naar "https://clickfarm.nl/back/resources.php" .. denk dat dat niet te bedoeling is.

Als je idd. AJAX achtige calls gaat maken met JavaScript, moet je er goed op letten dat je er niet overmatig & onnodig gebruik van maakt. Is ook helemaal niet nodig om deze call te maken als de gebruiker nog niet eens level 12 is en de market-row nog niet zichtbaar is.

**Comment by HermanRonk** [comment]
Dit had ik al opgelost, maar ik moet de commit zo nog even doen. Ik zal dan meteen ook een < lvl 12 check toevoegen.

De reden dat ik dit doe is overigens dat ik soms een NaN kaarde krijg meteen na het laden, die verdwijnt opzich vanzelf, maar dit is sneller.

            if (isNaN(objSalesInfo.eggs)) {NaNMarket = 0;} else {NaNMarket = 1;};
            if (NaNMarket = 1) {objMarket.show(); NaNMarket = 0;};
