### ISSUE TITLE
Na een refresh is handmatig kunststof maken onmogelijk

### ISSUE THREAD

**Issue by TommyboyNL** [HermanRonk/Clickfarm#34]
Situatie:
10.000 kunststoffabrieken
5.000 kunststofhelpers

Na een refresh is de "Maak kunststof" knop greyed-out. Een kunststofhelper aannemen en ontslaan (of in omgekeerde volgorde) lost dit probleem op tot de volgende reload.

**Comment by Marcade80** [comment]
Hmm kan het niet herproduceren. Codewise ziet het er ook goed uit. De status van de knop word bepaald door kunstfabrieken & helpers; dat word vanuit localstorage opgehaald en pas daarna word er gekeken of de knop enabled of disabled moet zijn.

**Comment by vvdaal** [comment]
Ik heb hier ook naar gekeken maar krijg het ook niet reproduceerbaar.

Kun je wellicht aangeven hoe wij dit kunnen reproduceren?

**Comment by TommyboyNL** [comment]
Tjah, bij mij is het een kwestie van op F5 klikken, en de bug is er weer. Browser is een volledig geüpdatete Firefox. Ook als ik vanaf we webconsole de betreffende knop oproep, krijg ik een error. Na een medewerker aangenomen of ontslagen te hebben werkt de knop zowel op de pagina als via de console.

**Comment by TommyboyNL** [comment]
Hier trouwens iemand die het zelfde rapporteert: https://gathering.tweakers.net/forum/list_message/54866277#54866277

**Comment by HermanRonk** [comment]
Wat is de error die je te zien krijgt in de console?

**Comment by TommyboyNL** [comment]
Ik krijg geen error, er gebeurt simpelweg niets. "makePlastic.click();" geeft een "<- undefined" terug, maar die krijg ik ook terug als ik de functie wél succesvol aanroep.

**Comment by TommyboyNL** [comment]
Zie ook de volgende screenshots:

![2018-08-07 18_58_20-clickfarm nl](https://user-images.githubusercontent.com/20584405/43790775-e91fe3ca-9a73-11e8-8087-5b3283c157b0.png)
![2018-08-07 18_59_12-ontwikkelaarshulpmiddelen - clickfarm nl - https___clickfarm nl_](https://user-images.githubusercontent.com/20584405/43790815-0c99f8c2-9a74-11e8-8654-c16a1cde167a.png)

**Comment by vvdaal** [comment]
Heb je dit probleem ook in een incognito browser/tab? (Export/import je save game).
Volgens mij heb ik de bug in het verleden gezien maar was dit opgelost, ik gok dat je een oudere versie van base.js gebruikt welke nog in je cache hangt.

**Comment by HermanRonk** [comment]
Ik kan het probleem niet meer reproduceren en de code lijkt ook in orde.
