### ISSUE TITLE
Counts bij kopen Eieren/Staal/Afval splijtstofstaven kunnen negatief worden

### ISSUE THREAD

**Issue by yamahabest** [HermanRonk/Clickfarm#36]
Ik heb geen idee hoe het gekomen is. Ik heb nooit iets gekocht via de bij behorende knoppen.

![image](https://user-images.githubusercontent.com/17543838/43684998-10980920-98ab-11e8-955d-acb1c33cea9a.png)

**Comment by HermanRonk** [comment]
Dat gebeurt wanneer de waardes te groot worden (nu even op 0 gezet, dus voor nu is het probleem even opgelost).

Ik zal een houdbaarheid aan de verschillende grondstoffen hangen en zo dagelijks het overschot "verkopen"

**Comment by HermanRonk** [comment]
Dit zou niet meer voor mogen komen. (opgelost in backend)
